# Generated by Django 5.0 on 2023-12-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bids_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='whishlist',
            field=models.BooleanField(default=False),
        ),
    ]
