# Generated by Django 5.0 on 2024-01-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bids_bid_alter_bids_whishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='catogeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogery', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Kitchen', 'Home & Kitchen'), ('Books & Media', 'Books & Media'), ('Health & Beauty', 'Health & Beauty'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Toys & Games', 'Toys & Games'), ('Grocery & Gourmet Food', 'Grocery & Gourmet Food')], max_length=100)),
                ('prodouct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.items')),
            ],
        ),
    ]
