# Generated by Django 5.0 on 2023-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodouct_name', models.CharField(max_length=255)),
                ('prodouct_id', models.IntegerField()),
            ],
        ),
    ]
