# Generated by Django 5.0 on 2023-12-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raja', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='prod',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
