# Generated by Django 5.0 on 2023-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raja', '0004_info_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='prodouct_id',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='info',
            name='seller_id',
            field=models.IntegerField(verbose_name='seller id'),
        ),
    ]
